'use babel';

import path from 'path';

export default class {
  static get directoryPath() {
    return path.resolve(__dirname, '../fixtures');
  }
  static get directoryForAutoGeneratedPath() {
    return path.resolve(this.directoryPath, 'auto-generated');
  }
  
  static get sampleTextPath() {
    return this.absolutify('sample.html');
  }
  static get largeTextPath() {
    return this.absolutifyAutoGenerated('large.html');
  }
  static get deepTextPath() {
    return this.absolutifyAutoGenerated('deep.html');
  }

  static absolutify(relativePath) {
     return path.resolve(this.directoryPath, relativePath);
  }
  static absolutifyAutoGenerated(relativePath) {
    return path.resolve(this.directoryForAutoGeneratedPath, relativePath);
  }
}
