'use babel';

import path from 'path';

const directoryPath
  = path.resolve(__dirname, '../fixtures');
const directoryForAutoGeneratedPath
  = path.resolve(directoryPath, 'auto-generated');

export default class FixturesPath {
  static DIRECTORY_PATH = directoryPath;
  static DIRECTORY_FOR_AUTO_GENERATED_PATH = directoryForAutoGeneratedPath;

  static get sampleTextPath() {
    return this.absolutify('sample.html');
  }
  static get largeTextPath() {
    return this.absolutifyAutoGenerated('large.html');
  }
  static get deepTextPath() {
    return this.absolutifyAutoGenerated('deep.html');
  }

  static absolutify(relativePath) {
     return path.resolve(this.DIRECTORY_PATH, relativePath);
  }
  static absolutifyAutoGenerated(relativePath) {
    return path.resolve(this.DIRECTORY_FOR_AUTO_GENERATED_PATH, relativePath);
  }
}
