'use babel';

import fs from 'fs-plus';
import FixturesPath from '../constants/fixtures-path';

/**
 * @callback writeContentsCallback
 * @param {WriteStream} writeStream
 * @return {undefined}
 */
/**
 * Common process to create text.
 * @param {string} createdPath
 * @param {writeContentsCallback} writeContents
 * @return {Promise.<undefined>} - To create a file.
 */
export default async function(createdPath, writeContents) {
  
  const dirPath = FixturesPath.directoryForAutoGeneratedPath;

  if (fs.existsSync(createdPath)) {
    // Delete an old file.
    fs.removeSync(createdPath);

  } else if (!fs.existsSync(dirPath)) {
    // Create a directory for auto generated files.
    fs.mkdirSync(dirPath);
  }

  // Return a promise to create a file.
  return new Promise((resolve) => {

    // NOTE: Use a write stream cuz of small memory usage.
    const ws = fs.createWriteStream(createdPath);
    // The promise is resolved when a write stream is closed.
    ws.on('close', () => resolve());

    writeContents(ws);

    ws.end();

  });
}
